name: Test and Publish

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  test-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8'

      - name: Cache dependencies
        uses: actions/cache@v4.0.0
        with:
          path: ~/.nuget
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Install dependencies
        run: dotnet restore

  publish-project:
    runs-on: ubuntu-latest
    needs: test-project
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8'

      - name: Cache dependencies
        uses: actions/cache@v4.0.0
        with:
          path: ~/.nuget
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Install dependencies
        run: dotnet restore
