name: Test and Publish

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  test-project:
    runs-on: ubuntu-latest

    steps:
      - name: Cheout
        uses: actions/checkout@4.1.1
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8'
      - name: Install dependencies
        run: dotnet restore

  publish-project:
    runs-on: ubuntu-latest
    needs: test-project
    steps:
      - name: Cheout
        uses: actions/checkout@4.1.1
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8'
      - name: Install dependencies
        run: dotnet restore
